### PR TITLE
change simpspector binary location & fix path to binaries

### PR DESCRIPTION
**Pull request by DavidBadura**
* [x] move simpspector binary into bin folder
* [x] update binaries path
* [x] fix security-checker
* [x] give up to build a phar file...

### CODE REVIEW

**Comment by DavidBadura** [comment]
ready...

**Comment by tolry** [comment]
:+1:

"give up to build a phar file ..." <--- didn't get box to run properly? We can do this in a separate PR anyway, no hurries there.

**Comment by DavidBadura** [comment]
the problem is, you can't execute binaries phar package. So the gadgets `phpmd`, `phpcs` and `security-checker` don't work :-( 

``` bash
> phar:///var/www/simpspector-analyser/simpspector.phar/bin/phpmd
```

**Comment by tolry** [comment]
Ah, ok - didn't know that, that's too bad. We need another :+1: to merge @simplethings/simpspector

**Comment by larsborn** [comment]
so do we leave it as an open issue? Maybe, we find a similar solution to this problem (like ... extracting and then executing or something).

+1 for merge from me.

**Comment by tolry** [comment]
I will open an issue for packaging

**Pull request merged**
